### ISSUE TITLE
Remove the 'fucking'

### ISSUE THREAD

**Issue by digibake** [andreasonny83/unique-names-generator#13]
This is a good library, but the 'fucking' adjective is too far in my opinion and should be removed.

/lib/dictionaries/adjectives.ts  line 903

I used the library to generate data for a quick mockup and it created "fucking_black_beaver" during a demonstration. It did not go down well.

**Comment by duraltelfer** [comment]
lmfao - went down well here

**Comment by andreasonny83** [comment]
@digibake ,
wow, I really never notice that. Thanks a lot for pointing that out. I'll prioritize this and will release a patched version shortly.
Thanks again

**Comment by andreasonny83** [comment]
Fixed in v3.0.1. Thanks again @digibake.
https://github.com/andreasonny83/unique-names-generator/releases/tag/v3.0.1

**Comment by digibake** [comment]
Thanks @andreasonny83, this is a really useful package. Such great work.
