### ISSUE TITLE
[Feature Request] : Option to have capital first letter

### ISSUE THREAD

**Issue by ajainuary** [andreasonny83/unique-names-generator#14]
I couldn't find any option to have the first letter capital of the username.
Eg. "Big Donkey"
I'd be happy to contribute by implementing this feature.

**Comment by andreasonny83** [comment]
Hey @ajainuary ,
thanks for this feature request.
I really like your proposal and I will let you know once it's ready.
Thank you again

**Comment by andreasonny83** [comment]
@ajainuary  A new `style` option is now available starting from v.3.1.0 
https://github.com/andreasonny83/unique-names-generator/releases/tag/v3.1.0

https://github.com/andreasonny83/unique-names-generator#style
