### ISSUE TITLE
dictionary of numbers

### ISSUE THREAD

**Issue by ravz** [andreasonny83/unique-names-generator#31]
would be nice to specify a dictionary of numbers with variable length, without having to create it ourselves as a custom dictionary

to create names such as `DangerousSnake456`

**Comment by andreasonny83** [comment]
That's an interesting one @ravz .
I can implement that.
I'll keep you posted

**Comment by andreasonny83** [comment]
@ravz  I implemented the numbers dictionary. Have a look at the doc here: https://github.com/andreasonny83/unique-names-generator#numbers-dictionary
Let me know if that correctly solves your issue.

**Comment by ravz** [comment]
Perfect! Thank you
