### ISSUE TITLE
[Feature Request] :  - Support for External Dictionaries 

### ISSUE THREAD

**Issue by abhijitmehta** [andreasonny83/unique-names-generator#5]
As a user, I should be able to pass my own dictionaries to get my preferred style of random names . 
Example. 
Following input should generate random names like  "Brash_ProfessorX" , "Goldern_Wolverine" etc. i.e. formed out of combination of randomly selected values for each key in the input JSON

> {
      "ADJECTIVES":[  
                  "Abrasive",
                  "Brash",
                  "Callous",
                  "Daft",
                  "Eccentric",
                  "Fiesty",
                  "Golden",
                  "Holy",
                  "Ignominious",
                  "Joltin",
                  "Killer",
                  "Luscious",
                  "Mushy",
                  "Nasty",
                  "OldSchool",
                  "Pompous",
                  "Quiet",
                  "Rowdy",
                  "Sneaky",
                  "Tawdry",
                  "Unique",
                  "Vivacious",
                  "Wicked",
                  "Xenophobic",
                  "Yawning",
                  "Zesty"
       ],
       " XMEN":[  
                  "ProfessorX",
                  "Beast",
                  "Colossus",
                  "Cyclops",
                  "Iceman",
                  "MarvelGirl",
                  "Storm",
                  "Wolverine",
                  "Shadowcat",
                  "Nightcrawler",
                  "Rogue",
                  "Angel",
                  "Dazzler",
                  "Syndicate",
                  "Magician",
                  "Bishop",
                  "Pyro",
                  "Psylocke",
                  "Toad",
                  "Firestar"
   ]
}

**Comment by andreasonny83** [comment]
closed by #12

**Comment by andreasonny83** [comment]
https://github.com/andreasonny83/unique-names-generator/releases/tag/v3.0.0
