### ISSUE TITLE
Min and max length 

### ISSUE THREAD

**Issue by luluhoc** [andreasonny83/unique-names-generator#58]
Is there an option to get a unique name within 3 to 20 characters?

**Comment by ErraticFox** [comment]
@patrykmaron you figure out anything? My only thought would be to manually grab the longest words in the dictionaries I'm using and figure it out lol

**Comment by patrykmaron** [comment]
> @patrykmaron you figure out anything? My only thought would be to manually grab the longest words in the dictionaries I'm using and figure it out lol

Can't remember, I think only option I found was custom dictionary composed of approved options.
